#!/usr/bin/env php
<?php

require 'vendor/autoload.php';

use Artack\SymlinkBundle\Command\SymlinkAbsolutToRelativCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new SymlinkAbsolutToRelativCommand);
$application->run();